services:
  pg_sql:
    image: postgres:16-alpine
    env_file:
        - ./backend/.env
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_PORT=5432
    ports:
      - 8000:8000
    depends_on:
      pg_sql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4200:80
    depends_on:
      - backend

volumes:
  postgres_data:
