"""add hikes and stations

Revision ID: d5811620dff2
Revises: 5166be3b29fb
Create Date: 2026-06-17 16:24:47.731522

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d5811620dff2"
down_revision: Union[str, Sequence[str], None] = "5166be3b29fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("CREATE EXTENSION IF NOT EXISTS cube")
    op.execute("CREATE EXTENSION IF NOT EXISTS earthdistance")

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "stations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("db_eva_id", sa.VARCHAR(length=20), nullable=True),
        sa.Column("operator", sa.VARCHAR(length=120), nullable=True),
        sa.Column("is_private_railway", sa.Boolean(), nullable=False),
        sa.Column("dticket_valid", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hikes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), nullable=False),
        sa.Column("description", sa.VARCHAR(length=250), nullable=True),
        sa.Column("sport", sa.Enum("hike", "bike", "run", name="sport_type"), nullable=False),
        sa.Column("distance_km", sa.Float(), nullable=False),
        sa.Column("duration_min", sa.Integer(), nullable=False),
        sa.Column("ascent_m", sa.Integer(), nullable=True),
        sa.Column("difficulty", sa.VARCHAR(length=20), nullable=True),
        sa.Column("start_lat", sa.Float(), nullable=False),
        sa.Column("start_lon", sa.Float(), nullable=False),
        sa.Column("end_lat", sa.Float(), nullable=True),
        sa.Column("end_lon", sa.Float(), nullable=True),
        sa.Column("is_loop", sa.Boolean(), nullable=False),
        sa.Column("geometry", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("region", sa.VARCHAR(length=80), nullable=False),
        sa.Column("start_station_id", sa.Uuid(), nullable=True),
        sa.Column("end_station_id", sa.Uuid(), nullable=True),
        sa.Column("source_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("attribution", sa.VARCHAR(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["end_station_id"],
            ["stations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["start_station_id"],
            ["stations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hikes_region"), "hikes", ["region"], unique=False)
    # ### end Alembic commands ###
    op.execute(
        "CREATE INDEX ix_hikes_start_earth ON hikes USING gist (ll_to_earth(start_lat, start_lon))"
    )


def downgrade():
    op.execute("DROP INDEX IF EXISTS ix_hikes_start_earth")
    op.drop_table("hikes")
    op.drop_table("stations")
    op.execute("DROP TYPE IF EXISTS sport_type")
