on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: docker/login-action@v3
          with: 
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - uses: docker/build-push-action@v6
          with: 
            context: ./backend
            push: true
            tags: ghcr.io/tiann317/weeknd-backend:latest

        - uses: docker/build-push-action@v6
          with: 
            context: ./frontend
            push: true
            tags: ghcr.io/tiann317/weeknd-frontend:latest
